openapi: 3.0.0
info:
  description: The best crypto and stock trading simulator
  version: "1.0.0"
  title: API for TP
tags:
  - name: accounts
    description: ...and everything related to them
  # - name: developers
  #   description: Operations available to regular developers
paths:
  /register:
    post:
      tags:
        - accounts
      summary: registers a new account
      operationId: register
      description: Create a new user account with provided credentials
      parameters:
        - in: query
          name: email
          description: email address
          required: true
          schema:
            type: string
        - in: query
          name: username
          description: username for the account
          required: true
          schema:
            type: string
        - in: query
          name: password
          description: password for the account
          required: true
          schema:
            type: string
      responses:
        "201":
          description: account registered
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: email or username is not unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      example: "not unique"
        "500":
          description: internal server error

components:
  schemas:
    User:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
          example: username
        email:
          type: string
          example: username@gmail.com
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MISOPOSTULKA/TP-trading-platform/1.0.0
